#!/usr/bin/env Rscript
library(knitr)
knit('starter.Rnw',tangle=TRUE)
knit('starter.Rnw',tangle=FALSE)
for ( i in c(1,2,3) ) {
  system('pdflatex starter ')
  system('bibtex starter ')
}
system('rm *log *aux *blg *bbl *spl')

